usb: Add soong_namespace to avoid build conflicts for now
example:
error: device/xiaomi/raphael/rootdir: MODULE.TARGET.ETC.init.qcom.usb.rc already defined by vendor/qcom/opensource/usb/etc.

Change-Id: I7d683a5d14be2acc70d53bef7188550be336506f